# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - production

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"

  - task: DownloadSecureFile@1
    name: envFile
    displayName: "Download .env file"
    inputs:
      secureFile: ".env-obs-production"

  - task: CopyFiles@2
    displayName: "Copy .env-obs-production file to: $(System.DefaultWorkingDirectory)"
    inputs:
      SourceFolder: "$(Agent.TempDirectory)"
      Contents: .env-obs-production
      TargetFolder: "$(System.DefaultWorkingDirectory)"

  - script: mv $(System.DefaultWorkingDirectory)/.env-obs-production $(System.DefaultWorkingDirectory)/.env
    displayName: "Rename .env-obs-production to .env"

  - script: npm run build
    displayName: "npm install and build"
  - task: ArchiveFiles@2
    displayName: "Archive Frontend Package"
    inputs:
      rootFolderOrFile: "dist/spa"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/OBS_app.zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts"
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "Obs-Frontend-Production"
